[workspace]
authors = ["The GeoJupyter Community"]
channels = ["conda-forge"]
name = "events.geojupyter.org"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
render = "myst build --html"
preview = "myst start"

[dependencies]
mystmd = ">=1.7.0,<2"
